### ISSUE TITLE
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined"

### ISSUE THREAD

**Issue by iuri** [RubensMario/personal-finance-app#1]
Hello Robson,
After downloading your code and running installation procedures as per your documentation, I've got the following error. 
It seems .env file has been missing and I"d like to know how you se tup your mongoDB environment. 

How do I fix the error? 

Best wishes,
I

 yarn start
yarn run v1.22.5
$ node index.js
Iniciando conexão ao MongoDB...
/Users/iuri/Apps/personal-finapp/node_modules/mongoose/lib/connection.js:582
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/Users/iuri/Apps/personal-finapp/node_modules/mongoose/lib/connection.js:582:11)
    at Mongoose.connect (/Users/iuri/Apps/personal-finapp/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/Users/iuri/Apps/personal-finapp/index.js:44:10)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by RubensMario** [comment]
Hi, Iuri!

You can get your connection string in your MongoDB management page, using
the Connect To Cluster menu. But the string structure is:
mongodb+srv://<user>:<password>@
cluster0.p4cph.mongodb.net/myDatabase?retryWrites=true&w=majority

I'm grateful by your feedback and you can contact me for other questions.
PS: I will add a .env example file in my project as soon as possible.


Best wishes,
Rubens Mario.


Em dom., 27 de mar. de 2022 às 15:41, Iuri de Araujo <
***@***.***> escreveu:

**Comment by brcra0019** [comment]
Thanks Rubens,
In fact, I've amended your code and solve the connection issue.
Thanks for the feedback
Best wishes,
I

**Comment by iuri** [comment]
Thanks Rubens,
In fact, I've amended your code and solve the connection issue.
Thanks for the feedback
Best wishes,
I
